name: Cypress Tests

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Cypress con reportes
        run: npm run report

      - name: Subir reportes como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports/
