name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and generate report
        run: npm run report:full

      - name: Crear portada index.html con fecha y hora
        run: |
          echo "<html><head><title>Reporte Swag Labs</title></head><body>" > cypress/reports/mochawesome/index.html
          echo "<h1>Reporte de Pruebas Swag Labs</h1>" >> cypress/reports/mochawesome/index.html
          echo "<p>Última ejecución: $(date -u)</p>" >> cypress/reports/mochawesome/index.html
          echo "<a href='report.html'>Ver reporte Mochawesome</a>" >> cypress/reports/mochawesome/index.html
          echo "</body></html>" >> cypress/reports/mochawesome/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RP_TOKEN }}
          publish_dir: ./cypress/reports/mochawesome
